// ── Kara Burd — Skaled SDR ──────────────────────────────────────
export const REP = {
  name: "Kara Burd",
  title: "Sales Development Representative",
  company: "Skaled Consulting",
  quarter: "Q2 2026",
  weekLabel: "Week 1 of 13",
  quotaPipeline: 180000,
  pipelineGenerated: 47500,
  meetingsTarget: 20,
  meetingsBooked: 6,
  emailsSentToday: 34,
  callsMadeToday: 12,
  linkedInTouchesToday: 8,
  repliesReceivedToday: 4,
  activitiesToday: 54,
  activitiesGoalDaily: 75,
  emailReplyRate: 14.2,
  industryAvgReply: 8.5,
  callConnectRate: 18.5,
  meetingConversionRate: 38,
};

// ── Daily Action Plan — what Kara should do today ──────────────
export const DAILY_ACTIONS = [
  {
    id: "a1",
    type: "follow-up",
    priority: "critical",
    title: "Follow up with Marcus Chen — Beacon Therapeutics",
    subtitle: "Replied to Sequence 3, Step 4 yesterday. Expressed interest in RevOps assessment.",
    contact: "Marcus Chen",
    company: "Beacon Therapeutics",
    role: "VP of Sales Operations",
    channel: "email",
    dueTime: "9:00 AM",
    suggestedAction: "Send case study on life sciences RevOps transformation. Reference his pain point around forecasting accuracy.",
    status: "pending",
  },
  {
    id: "a2",
    type: "call",
    priority: "critical",
    title: "Call back Sarah Okafor — Nuveen Capital",
    subtitle: "Requested a call on LinkedIn. High-intent — visited pricing page 3x this week.",
    contact: "Sarah Okafor",
    company: "Nuveen Capital",
    role: "CRO",
    channel: "phone",
    dueTime: "10:00 AM",
    suggestedAction: "Prep: They're a PE-backed fintech, 200 employees, just raised Series C. Lead with scalable sales process pitch.",
    status: "pending",
  },
  {
    id: "a3",
    type: "sequence",
    priority: "high",
    title: "Add 15 new contacts to 'RevOps Assessment' sequence",
    subtitle: "Sequence is running low on active prospects. Pull from Salesforce 'Marketing Qualified' list.",
    contact: null,
    company: null,
    role: null,
    channel: "outreach",
    dueTime: "11:00 AM",
    suggestedAction: "Filter for VP+ titles at companies with 100-500 employees. Prioritize SaaS and fintech verticals.",
    status: "pending",
  },
  {
    id: "a4",
    type: "follow-up",
    priority: "high",
    title: "Re-engage David Park — Tessera Analytics",
    subtitle: "Went dark after meeting 2 weeks ago. Opened last email 3x but no reply.",
    contact: "David Park",
    company: "Tessera Analytics",
    role: "Head of Revenue",
    channel: "email",
    dueTime: "1:00 PM",
    suggestedAction: "Try a breakup email with a soft CTA. Mention the ROI calculator as a no-commitment next step.",
    status: "pending",
  },
  {
    id: "a5",
    type: "linkedin",
    priority: "medium",
    title: "Engage with 5 target accounts on LinkedIn",
    subtitle: "Comment on posts from decision-makers at Apex Growth, Helix Software, Ridgeline AI, Polaris Data, NorthStar SaaS.",
    contact: null,
    company: null,
    role: null,
    channel: "linkedin",
    dueTime: "2:00 PM",
    suggestedAction: "Leave thoughtful comments (not salesy). Build familiarity before outbound sequence starts next week.",
    status: "pending",
  },
  {
    id: "a6",
    type: "call",
    priority: "medium",
    title: "Power dial 20 contacts from 'Cold Outbound - SaaS' list",
    subtitle: "Calls scheduled for afternoon block. Script: 'Skaled growth diagnostic' opener.",
    contact: null,
    company: null,
    role: null,
    channel: "phone",
    dueTime: "3:00 PM",
    suggestedAction: "Focus on Director+ titles. Track connect rate — goal is 4+ conversations from 20 dials.",
    status: "pending",
  },
  {
    id: "a7",
    type: "follow-up",
    priority: "low",
    title: "Send recap to Amy Tran — CloudBridge Solutions",
    subtitle: "Had an intro call Monday. Needs a follow-up with next steps and proposal link.",
    contact: "Amy Tran",
    company: "CloudBridge Solutions",
    role: "Director of Sales Enablement",
    channel: "email",
    dueTime: "4:00 PM",
    suggestedAction: "Include meeting notes, propose a discovery call with Jake for next week. Attach the Skaled services one-pager.",
    status: "pending",
  },
  {
    id: "a8",
    type: "admin",
    priority: "low",
    title: "Update Salesforce — log all activities from today",
    subtitle: "End-of-day CRM hygiene. Ensure all calls, emails, and meetings are logged.",
    contact: null,
    company: null,
    role: null,
    channel: "salesforce",
    dueTime: "5:00 PM",
    suggestedAction: "Update contact statuses, move qualified leads to 'Discovery' stage, add notes from conversations.",
    status: "pending",
  },
];

// ── Outreach Sequences Performance ─────────────────────────────
export const SEQUENCES = [
  {
    name: "RevOps Assessment Offer",
    status: "active",
    activeProspects: 87,
    totalEnrolled: 142,
    openRate: 62.3,
    replyRate: 18.7,
    meetingsBooked: 8,
    avgDaysToReply: 2.1,
    steps: 5,
  },
  {
    name: "Cold Outbound — SaaS VP+",
    status: "active",
    activeProspects: 64,
    totalEnrolled: 210,
    openRate: 48.1,
    replyRate: 11.2,
    meetingsBooked: 6,
    avgDaysToReply: 3.4,
    steps: 7,
  },
  {
    name: "Inbound Follow-Up (MQL)",
    status: "active",
    activeProspects: 23,
    totalEnrolled: 45,
    openRate: 78.4,
    replyRate: 32.1,
    meetingsBooked: 9,
    avgDaysToReply: 0.8,
    steps: 3,
  },
  {
    name: "Event Follow-Up — SaaStr 2026",
    status: "paused",
    activeProspects: 0,
    totalEnrolled: 56,
    openRate: 55.2,
    replyRate: 14.8,
    meetingsBooked: 4,
    avgDaysToReply: 2.9,
    steps: 4,
  },
  {
    name: "Re-Engagement — Lost Opps",
    status: "active",
    activeProspects: 31,
    totalEnrolled: 78,
    openRate: 44.6,
    replyRate: 9.3,
    meetingsBooked: 2,
    avgDaysToReply: 4.1,
    steps: 5,
  },
];

// ── Top Performing Touchpoints ─────────────────────────────────
export const TOP_TOUCHPOINTS = [
  { type: "email", name: "RevOps Assessment — Step 1 (Pain Intro)", replyRate: 24.3, sent: 142, replies: 35, meetings: 8 },
  { type: "email", name: "Inbound MQL — Step 1 (Same-Day Reply)", replyRate: 38.6, sent: 45, replies: 17, meetings: 9 },
  { type: "email", name: "Cold SaaS — Step 3 (Case Study)", replyRate: 15.1, sent: 186, replies: 28, meetings: 4 },
  { type: "linkedin", name: "LinkedIn Voice Note (Connection Request)", replyRate: 22.0, sent: 50, replies: 11, meetings: 3 },
  { type: "call", name: "Cold Call — Growth Diagnostic Opener", connectRate: 18.5, dials: 240, conversations: 44, meetings: 6 },
  { type: "email", name: "Breakup Email — ROI Calculator CTA", replyRate: 12.8, sent: 78, replies: 10, meetings: 2 },
];

// ── SFDC Pipeline (Opportunities) ──────────────────────────────
export const OPPORTUNITIES = [
  {
    id: "opp1",
    name: "Beacon Therapeutics — RevOps Engagement",
    account: "Beacon Therapeutics",
    contact: "Marcus Chen",
    amount: 42000,
    stage: "Discovery",
    probability: 25,
    closeDate: "2026-06-15",
    lastActivity: "2026-04-01",
    nextStep: "Schedule discovery call with Jake",
    daysInStage: 3,
    source: "Outbound — Sequence",
  },
  {
    id: "opp2",
    name: "CloudBridge Solutions — Sales Enablement",
    account: "CloudBridge Solutions",
    contact: "Amy Tran",
    amount: 35000,
    stage: "Qualification",
    probability: 15,
    closeDate: "2026-07-01",
    lastActivity: "2026-03-31",
    nextStep: "Send proposal + schedule discovery",
    daysInStage: 5,
    source: "Inbound — Website",
  },
  {
    id: "opp3",
    name: "Nuveen Capital — Scalable Sales Process",
    account: "Nuveen Capital",
    contact: "Sarah Okafor",
    amount: 65000,
    stage: "Discovery",
    probability: 30,
    closeDate: "2026-06-30",
    lastActivity: "2026-04-02",
    nextStep: "Intro call today — she requested callback",
    daysInStage: 1,
    source: "Inbound — LinkedIn",
  },
  {
    id: "opp4",
    name: "Tessera Analytics — Revenue Operations",
    account: "Tessera Analytics",
    contact: "David Park",
    amount: 28000,
    stage: "Stalled",
    probability: 10,
    closeDate: "2026-06-01",
    lastActivity: "2026-03-19",
    nextStep: "Re-engage with breakup email",
    daysInStage: 14,
    source: "Outbound — Sequence",
  },
  {
    id: "opp5",
    name: "Apex Growth Partners — GTM Strategy",
    account: "Apex Growth Partners",
    contact: "Lena Vasquez",
    amount: 55000,
    stage: "Proposal",
    probability: 50,
    closeDate: "2026-05-15",
    lastActivity: "2026-03-28",
    nextStep: "Awaiting proposal review — follow up Friday",
    daysInStage: 8,
    source: "Referral",
  },
];

// ── SFDC Recent Activities ─────────────────────────────────────
export const RECENT_ACTIVITIES = [
  { date: "2026-04-02", type: "email", subject: "Re: RevOps Assessment for Beacon", contact: "Marcus Chen", company: "Beacon Therapeutics", direction: "inbound" },
  { date: "2026-04-02", type: "call", subject: "Cold call — connected, scheduled callback", contact: "James Liu", company: "Ridgeline AI", direction: "outbound" },
  { date: "2026-04-02", type: "email", subject: "Sent case study: SaaS RevOps transformation", contact: "Priya Nair", company: "Helix Software", direction: "outbound" },
  { date: "2026-04-01", type: "linkedin", subject: "LinkedIn connection accepted", contact: "Sarah Okafor", company: "Nuveen Capital", direction: "inbound" },
  { date: "2026-04-01", type: "meeting", subject: "Intro call — discussed sales enablement needs", contact: "Amy Tran", company: "CloudBridge Solutions", direction: "outbound" },
  { date: "2026-04-01", type: "email", subject: "Follow-up: growth diagnostic results", contact: "Tom Wallace", company: "NorthStar SaaS", direction: "outbound" },
  { date: "2026-03-31", type: "call", subject: "Discovery call — qualified for RevOps", contact: "Marcus Chen", company: "Beacon Therapeutics", direction: "outbound" },
  { date: "2026-03-31", type: "email", subject: "Breakup email sent", contact: "David Park", company: "Tessera Analytics", direction: "outbound" },
  { date: "2026-03-28", type: "meeting", subject: "Proposal review with Lena", contact: "Lena Vasquez", company: "Apex Growth Partners", direction: "outbound" },
  { date: "2026-03-28", type: "email", subject: "Inbound inquiry — pricing page visit", contact: "Rachel Kim", company: "Polaris Data", direction: "inbound" },
];

// ── SFDC Key Accounts ──────────────────────────────────────────
export const ACCOUNTS = [
  { name: "Beacon Therapeutics", industry: "Life Sciences / SaaS", employees: 180, status: "Active Opp", contacts: 3, lastTouch: "2026-04-02" },
  { name: "Nuveen Capital", industry: "Fintech", employees: 200, status: "Active Opp", contacts: 2, lastTouch: "2026-04-02" },
  { name: "CloudBridge Solutions", industry: "Cloud Infrastructure", employees: 320, status: "Active Opp", contacts: 1, lastTouch: "2026-03-31" },
  { name: "Apex Growth Partners", industry: "Growth Equity", employees: 85, status: "Active Opp", contacts: 2, lastTouch: "2026-03-28" },
  { name: "Tessera Analytics", industry: "Data Analytics", employees: 150, status: "Stalled", contacts: 1, lastTouch: "2026-03-19" },
  { name: "Ridgeline AI", industry: "AI / ML", employees: 95, status: "Prospecting", contacts: 1, lastTouch: "2026-04-02" },
  { name: "Helix Software", industry: "SaaS", employees: 240, status: "Prospecting", contacts: 2, lastTouch: "2026-04-02" },
  { name: "Polaris Data", industry: "Data Infrastructure", employees: 110, status: "Prospecting", contacts: 1, lastTouch: "2026-03-28" },
  { name: "NorthStar SaaS", industry: "SaaS", employees: 175, status: "Prospecting", contacts: 1, lastTouch: "2026-04-01" },
];

// ── SFDC Leads ─────────────────────────────────────────────────
export const LEADS = [
  { name: "James Liu", company: "Ridgeline AI", title: "VP of Sales", status: "Working", source: "Cold Call", score: 72, lastTouch: "2026-04-02" },
  { name: "Priya Nair", company: "Helix Software", title: "Director of Revenue Ops", status: "Working", source: "Outbound Email", score: 65, lastTouch: "2026-04-02" },
  { name: "Rachel Kim", company: "Polaris Data", title: "Head of GTM", status: "New", source: "Inbound — Website", score: 58, lastTouch: "2026-03-28" },
  { name: "Tom Wallace", company: "NorthStar SaaS", title: "CRO", status: "Working", source: "Outbound Email", score: 61, lastTouch: "2026-04-01" },
  { name: "Megan Cho", company: "Verdant Health", title: "SVP Sales", status: "New", source: "LinkedIn", score: 45, lastTouch: "2026-03-30" },
  { name: "Andre Brooks", company: "Crestline Financial", title: "VP RevOps", status: "New", source: "Referral", score: 78, lastTouch: "2026-03-29" },
];

// ── Weekly Trend Data ──────────────────────────────────────────
export const WEEKLY_ACTIVITY = [
  { day: "Mon", emails: 38, calls: 15, linkedin: 6, replies: 5 },
  { day: "Tue", emails: 42, calls: 18, linkedin: 10, replies: 6 },
  { day: "Wed", emails: 34, calls: 12, linkedin: 8, replies: 4 },
  { day: "Thu", emails: 0, calls: 0, linkedin: 0, replies: 0 },
  { day: "Fri", emails: 0, calls: 0, linkedin: 0, replies: 0 },
];

export const PIPELINE_WEEKLY = [
  { week: "W48", amount: 0 },
  { week: "W49", amount: 12000 },
  { week: "W50", amount: 12000 },
  { week: "W51", amount: 22000 },
  { week: "W52", amount: 28000 },
  { week: "W1", amount: 47500 },
];
